# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
before_install:
    - sudo apt-get install libmpfr-dev
sudo: false
cache: packages
r:
    - release
    - devel
r_packages:
    - covr
after_success:
    - Rscript -e 'covr::codecov()'